spring:
  application:
    name: ${person.query.name}

  security:
    user:
      name: ${person.query.security-user-name}
      password: ${person.query.security-user-password}

  jpa:
    database: ${person.query.db.database}
    show-sql: ${person.query.db.show-sql}
    hibernate:
      ddl-auto: none
  datasource:
    url: ${person.query.db.uri}
    username: ${person.query.db.username}
    password: ${person.query.db.password}

management:
  tracing:
    sampling:
      probability: ${person.otlp-tracing-sampling-probability}
  otlp:
    metrics:
      export:
        url: ${person.otlp-metrics-uri}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${person.otlp-tracing-uri}
    logging:
      export:
        otlp:
          endpoint: ${person.otlp-logging-uri}
  endpoints:
    web:
      exposure:
        include:
        - info
        - health

logging:
  pattern:
    correlation: ${person.logging-pattern-correlation}

springdoc:
  show-actuator: true
  swagger-ui:
    enabled: ${person.swagger-enabled}
  api-docs:
    enabled: ${person.swagger-enabled}

server:
  port: ${person.query.port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/