person:
  swagger-enabled: false
  swagger-central-uri: http://localhost:8090
  logging-pattern-correlation: "[ %X{traceId:-} %X{spanId:-} ] "

  otlp-metrics-uri: http://localhost:4318/v1/metrics
  otlp-logging-uri: http://localhost:4318/v1/logs
  otlp-tracing-uri: http://localhost:4318/v1/traces
  otlp-tracing-sampling-probability: 1.0
   
  query:
    name: PersonQueryAPIs
    port: 8092
    security-user-name: user_person_prod
    security-user-password: prod1234

    db:
      uri: jdbc:mysql://localhost:3306/n4smh_org
      database: mysql
      username: user_db_prod
      password: prod1234
      show-sql: false 

